Traceback (most recent call last):
  File "C:\Users\laram\AppData\Local\Continuum\anaconda3\envs\ca4015\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\laram\AppData\Local\Continuum\anaconda3\envs\ca4015\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\laram\AppData\Local\Continuum\anaconda3\envs\ca4015\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\laram\AppData\Local\Continuum\anaconda3\envs\ca4015\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\laram\AppData\Local\Continuum\anaconda3\envs\ca4015\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\laram\AppData\Local\Continuum\anaconda3\envs\ca4015\lib\site-packages\nbclient\client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "C:\Users\laram\AppData\Local\Continuum\anaconda3\envs\ca4015\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\Users\laram\AppData\Local\Continuum\anaconda3\envs\ca4015\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
model = build_model(user_artists, embedding_dim=30, init_stddev=0.5)
model.train(num_iterations=2000, learning_rate=10.)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_35908/460896045.py[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [0mmodel[0m [1;33m=[0m [0mbuild_model[0m[1;33m([0m[0muser_artists[0m[1;33m,[0m [0membedding_dim[0m[1;33m=[0m[1;36m30[0m[1;33m,[0m [0minit_stddev[0m[1;33m=[0m[1;36m0.5[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      2[0m [0mmodel[0m[1;33m.[0m[0mtrain[0m[1;33m([0m[0mnum_iterations[0m[1;33m=[0m[1;36m2000[0m[1;33m,[0m [0mlearning_rate[0m[1;33m=[0m[1;36m10.[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\AppData\Local\Temp/ipykernel_35908/3999473338.py[0m in [0;36mbuild_model[1;34m(ratings, embedding_dim, init_stddev)[0m
[0;32m      4[0m     [0mtrain_ratings[0m[1;33m,[0m [0mtest_ratings[0m [1;33m=[0m [0msplit_dataframe[0m[1;33m([0m[0mratings[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      5[0m     [1;31m# SparseTensor representation of the train and test datasets.[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 6[1;33m     [0mA_train[0m [1;33m=[0m [0mbuild_rating_sparse_tensor_ratings[0m[1;33m([0m[0mtrain_ratings[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      7[0m     [0mA_test[0m [1;33m=[0m [0mbuild_rating_sparse_tensor_ratings[0m[1;33m([0m[0mtest_ratings[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      8[0m     [1;31m# Initialize the embeddings using a normal distribution.[0m[1;33m[0m[1;33m[0m[0m

[1;31mNameError[0m: name 'build_rating_sparse_tensor_ratings' is not defined
NameError: name 'build_rating_sparse_tensor_ratings' is not defined

